Develop
ICESI-PI1/icesi-filantrop-a-equipo-2 pull request #41
Opened 2023-10-23 22:12 UTC by JacoboOssa

2023-10-23 22:18 UTC, yuluka requested changes
tests_load_scholarship_info.py has conflicts.

2023-10-23 22:48 UTC, AndresPin0 commented on crud/tests/tests_load_scholarship_info.py
> +<<<<<<< HEAD
Elimina eso puñeta

2023-10-23 22:48 UTC, AndresPin0 requested changes
Elimina eso puñeta

2023-10-26 22:27 UTC, Dennis-Spiderman requested changes

2023-10-26 22:27 UTC, Dennis-Spiderman commented on crud/tests/tests_load_scholarship_info.py
> +=======
Delete this please.

2023-10-30 21:52 UTC, merged